# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 17:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('u_id', models.IntegerField()),
                ('pro_id', models.CharField(max_length=2)),
                ('county_id', models.CharField(max_length=5)),
                ('town_id', models.CharField(max_length=7)),
                ('village_id', models.CharField(max_length=20)),
                ('v_name', models.CharField(max_length=50)),
                ('t_name', models.CharField(max_length=50)),
                ('c_name', models.CharField(max_length=50)),
                ('substitute', models.CharField(max_length=50)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
        ),
    ]
