# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 06:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_url', models.URLField()),
                ('photo_base64', models.TextField(default='')),
                ('source_type', models.TextField()),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('address', models.TextField(default='')),
                ('modified_address', models.TextField(default='')),
                ('village_name', models.TextField(default='')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualified_status', models.TextField(default='待審核')),
                ('location', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', geography=True, srid=4326)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
    ]
